version: '3.8'

services:
  db:
    image: mysql:8.0.33-debian
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: '256133' # TODO Security
      TZ: Asia/Tokyo
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - "./mysql/init/:/docker-entrypoint-initdb.d/"
      - "./mysql/config/mysql.cnf:/etc/mysql/conf.d/mysql.cnf"
  app:
    # image: maven:3.9.2-eclipse-temurin-17
    build:
      context: ./springboot
      dockerfile: Dockerfile
    container_name: springboot-app
    ports:
      - "8080:8080"
    volumes:
      # - "/Users/suzukiti/dev/JavaApp/project/:/home/"
      - "/c/Users/h4039/dev/JavaApp/poc-SpringBootApp/:/home/poc-SpringBootApp/"
    command: /bin/bash
    tty: true
    depends_on:
      - "db"
